blank_issues_enabled: false
contact_links:
  - name: Gatsby Documentation
    url: https://www.gatsbyjs.com/docs/
    about: Check out the Gatsby documentation for answers to common questions
  - name: Gatsby Discord
    url: http://gatsby.dev/discord
    about: Ask general questions about Gatsby that are not related to these themes
  - name: Questions
    url: https://github.com/LekoArts/gatsby-themes/discussions/categories/questions
    about: Usage question or discussion about any of the themes
  - name: Feature Requests
    url: https://github.com/LekoArts/gatsby-themes/discussions/categories/ideas-feature-requests
    about: Suggest an idea for this project or one of the themes
  - name: Suggest a new theme
    url: https://github.com/LekoArts/gatsby-themes/discussions/categories/ideas-feature-requests
    about: Have an idea for a new theme? Suggest it here
